// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: lvgl_esp

#include "ui.h"

// COMPONENT Container2

lv_obj_t * ui_Container2_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Container2;
    cui_Container2 = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Container2);
    lv_obj_set_width(cui_Container2, lv_pct(100));
    lv_obj_set_height(cui_Container2, lv_pct(100));
    lv_obj_set_align(cui_Container2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_TextArea1;
    cui_TextArea1 = lv_textarea_create(cui_Container2);
    lv_obj_set_width(cui_TextArea1, lv_pct(100));
    lv_obj_set_height(cui_TextArea1, lv_pct(100));
    lv_obj_set_align(cui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(cui_TextArea1, "Placeholder...");

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER2_NUM);
    children[UI_COMP_CONTAINER2_CONTAINER2] = cui_Container2;
    children[UI_COMP_CONTAINER2_TEXTAREA1] = cui_TextArea1;
    lv_obj_add_event_cb(cui_Container2, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Container2, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Container2_create_hook(cui_Container2);
    return cui_Container2;
}

