// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: lvgl_esp

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_tida = NULL;
lv_obj_t * ui_week = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_date = NULL;
lv_obj_t * ui_track = NULL;
lv_obj_t * ui_arti = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_tmpa = NULL;
lv_obj_t * ui_rha = NULL;
// event funtions
void ui_event_tida(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen3_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Screen1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_plaintxt);
    ui_object_set_themeable_style_property(ui_Screen1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_plaintxt);

    ui_Spinner1 = lv_spinner_create(ui_Screen1);
    //lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 66);
    lv_obj_set_x(ui_Spinner1, 15);
    lv_obj_set_y(ui_Spinner1, 102);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_rounded(ui_Spinner1, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_tida = lv_obj_create(ui_Screen1);
    lv_obj_set_height(ui_tida, 222);
    lv_obj_set_width(ui_tida, lv_pct(62));
    lv_obj_set_x(ui_tida, -86);
    lv_obj_set_y(ui_tida, -43);
    lv_obj_set_align(ui_tida, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tida, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_tida, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_tida, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_tida, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_plaintxt);
    ui_object_set_themeable_style_property(ui_tida, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_plaintxt);
    lv_obj_set_style_border_color(ui_tida, lv_color_hex(0x5B5601), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tida, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_tida, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_tida, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_tida, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_tida, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_week = lv_label_create(ui_tida);
    lv_obj_set_width(ui_week, lv_pct(97));
    lv_obj_set_height(ui_week, lv_pct(12));
    lv_obj_set_x(ui_week, -17);
    lv_obj_set_y(ui_week, -8);
    lv_obj_set_align(ui_week, LV_ALIGN_CENTER);
    lv_label_set_text(ui_week, "Weekday");
    lv_obj_set_style_text_color(ui_week, lv_color_hex(0xE3FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_week, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_week, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_week, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_tida);
    lv_obj_set_width(ui_time, lv_pct(100));
    lv_obj_set_height(ui_time, lv_pct(62));
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "WA:IT");
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0xCF5D0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_time, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &ui_font_DIGI2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_tida);
    lv_obj_set_width(ui_date, lv_pct(100));
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_date, -1);
    lv_obj_set_y(ui_date, 74);
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "Loading date...");
    lv_obj_set_style_text_color(ui_date, lv_color_hex(0x0BD797), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_date, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_track = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_track, lv_pct(101));
    lv_obj_set_height(ui_track, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_track, -1);
    lv_obj_set_y(ui_track, 99);
    lv_obj_set_align(ui_track, LV_ALIGN_CENTER);
    lv_label_set_text(ui_track, "Fetching... the title name of the song you are or were listening to");
    lv_obj_set_style_text_color(ui_track, lv_color_hex(0x8EB41D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_track, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_track, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_track, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_track, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_track, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_track, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_track, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_track, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_track, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arti = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_arti, lv_pct(100));
    lv_obj_set_height(ui_arti, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_arti, 1);
    lv_obj_set_y(ui_arti, 144);
    lv_obj_set_align(ui_arti, LV_ALIGN_CENTER);
    lv_label_set_text(ui_arti, "Fetching... the artist name");
    lv_obj_set_style_text_color(ui_arti, lv_color_hex(0x0F8689), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_arti, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_arti, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_arti, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel5, 161);
    lv_obj_set_height(ui_Panel5, 222);
    lv_obj_set_x(ui_Panel5, 149);
    lv_obj_set_y(ui_Panel5, -43);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x5B5601), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label11, lv_pct(120));
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 135);
    lv_obj_set_y(ui_Label11, -127);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Room Climate");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xCF1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tmpa = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_tmpa, lv_pct(118));
    lv_obj_set_height(ui_tmpa, lv_pct(22));
    lv_obj_set_x(ui_tmpa, -118);
    lv_obj_set_y(ui_tmpa, -394);
    lv_obj_set_align(ui_tmpa, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tmpa, "DHT temp");
    lv_obj_set_style_text_color(ui_tmpa, lv_color_hex(0xE37B30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tmpa, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_tmpa, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tmpa, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rha = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_rha, lv_pct(118));
    lv_obj_set_height(ui_rha, lv_pct(20));
    lv_obj_set_x(ui_rha, 153);
    lv_obj_set_y(ui_rha, 16);
    lv_obj_set_align(ui_rha, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rha, "DHT RH%");
    lv_obj_set_style_text_color(ui_rha, lv_color_hex(0xF8C166), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rha, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rha, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rha, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_tida, ui_event_tida, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Spinner1 = NULL;
    ui_tida = NULL;
    ui_week = NULL;
    ui_time = NULL;
    ui_date = NULL;
    ui_track = NULL;
    ui_arti = NULL;
    ui_Panel5 = NULL;
    ui_Label11 = NULL;
    ui_tmpa = NULL;
    ui_rha = NULL;

}
