// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: lvgl_esp

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_stabtn = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_psbtn = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_time1 = NULL;
lv_obj_t * ui_Spinner2 = NULL;
// event funtions
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_stabtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        startchrono(e);
        _ui_flag_modify(ui_Spinner2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_psbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pschrono(e);
        _ui_flag_modify(ui_Spinner2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screen3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Screen3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_Screen3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bgscreen);
    ui_object_set_themeable_style_property(ui_Screen3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bgscreen);

    ui_Panel3 = lv_obj_create(ui_Screen3);
    lv_obj_set_height(ui_Panel3, 50);
    lv_obj_set_width(ui_Panel3, lv_pct(97));
    lv_obj_set_x(ui_Panel3, -238);
    lv_obj_set_y(ui_Panel3, -183);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Stopwatch");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xA77B08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_button_create(ui_Panel3);
    lv_obj_set_width(ui_Button5, lv_pct(19));
    lv_obj_set_height(ui_Button5, lv_pct(200));
    lv_obj_set_x(ui_Button5, -28);
    lv_obj_set_y(ui_Button5, -277);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x685FAB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Home");

    ui_Panel8 = lv_obj_create(ui_Screen3);
    lv_obj_set_height(ui_Panel8, 96);
    lv_obj_set_width(ui_Panel8, lv_pct(97));
    lv_obj_set_x(ui_Panel8, -118);
    lv_obj_set_y(ui_Panel8, -28);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Panel8, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Panel8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "00 : 00 : 00");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x081FC9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Screen3);
    lv_obj_set_height(ui_Panel9, 72);
    lv_obj_set_width(ui_Panel9, lv_pct(97));
    lv_obj_set_x(ui_Panel9, 6);
    lv_obj_set_y(ui_Panel9, 59);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel9, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_stabtn = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_stabtn, lv_pct(30));
    lv_obj_set_height(ui_stabtn, lv_pct(120));
    lv_obj_set_align(ui_stabtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stabtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_stabtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_stabtn, lv_color_hex(0x38C51D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stabtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_stabtn, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_stabtn, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_stabtn);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "START");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_psbtn = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_psbtn, lv_pct(30));
    lv_obj_set_height(ui_psbtn, lv_pct(120));
    lv_obj_set_align(ui_psbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_psbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_psbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_psbtn, lv_color_hex(0xE29728), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_psbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_psbtn);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "PAUSE");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Screen3);
    lv_obj_set_height(ui_Panel10, 58);
    lv_obj_set_width(ui_Panel10, lv_pct(97));
    lv_obj_set_x(ui_Panel10, -47);
    lv_obj_set_y(ui_Panel10, 119);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel10, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time1 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_time1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_time1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time1, "12:56");
    lv_obj_set_style_text_font(ui_time1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner2 = lv_spinner_create(ui_Panel10);
    //lv_spinner_set_anim_params(ui_Spinner2, 1000, 90);
    lv_obj_set_width(ui_Spinner2, lv_pct(9));
    lv_obj_set_height(ui_Spinner2, lv_pct(172));
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Spinner2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Spinner2, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0xFF7940), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner2, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_stabtn, ui_event_stabtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_psbtn, ui_event_psbtn, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Panel3 = NULL;
    ui_Label7 = NULL;
    ui_Button5 = NULL;
    ui_Label12 = NULL;
    ui_Panel8 = NULL;
    ui_Label8 = NULL;
    ui_Panel9 = NULL;
    ui_stabtn = NULL;
    ui_Label9 = NULL;
    ui_psbtn = NULL;
    ui_Label10 = NULL;
    ui_Panel10 = NULL;
    ui_time1 = NULL;
    ui_Spinner2 = NULL;

}
