// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: lvgl_esp

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Spinner1;
extern void ui_event_tida(lv_event_t * e);
extern lv_obj_t * ui_tida;
extern lv_obj_t * ui_week;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_track;
extern lv_obj_t * ui_arti;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_tmpa;
extern lv_obj_t * ui_rha;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

