// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: lvgl_esp

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label7;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel9;
extern void ui_event_stabtn(lv_event_t * e);
extern lv_obj_t * ui_stabtn;
extern lv_obj_t * ui_Label9;
extern void ui_event_psbtn(lv_event_t * e);
extern lv_obj_t * ui_psbtn;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_time1;
extern lv_obj_t * ui_Spinner2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

