// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: lvgl_esp

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BGSCREEN 0
#define UI_THEME_COLOR_PLAINTXT 1
#define UI_THEME_COLOR_PANELBG 2
#define UI_THEME_COLOR_PNLBORDR 3

#define UI_THEME_DEFAULT 0

#define UI_THEME_LIGHT 1

#define UI_THEME_DARK 2

extern const ui_theme_variable_t _ui_theme_color_bgscreen[3];
extern const ui_theme_variable_t _ui_theme_alpha_bgscreen[3];

extern const ui_theme_variable_t _ui_theme_color_plaintxt[3];
extern const ui_theme_variable_t _ui_theme_alpha_plaintxt[3];

extern const ui_theme_variable_t _ui_theme_color_panelbg[3];
extern const ui_theme_variable_t _ui_theme_alpha_panelbg[3];

extern const ui_theme_variable_t _ui_theme_color_pnlbordr[3];
extern const ui_theme_variable_t _ui_theme_alpha_pnlbordr[3];

extern const uint32_t * ui_theme_colors[3];
extern const uint8_t * ui_theme_alphas[3];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
