// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: lvgl_esp

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_bgscreen[3] = {0x000000, 0xFFFFFF, 0x000000};
const ui_theme_variable_t _ui_theme_alpha_bgscreen[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_plaintxt[3] = {0x000000, 0x000000, 0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_plaintxt[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_panelbg[3] = {0x000000, 0xFFFFFF, 0x000000};
const ui_theme_variable_t _ui_theme_alpha_panelbg[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_pnlbordr[3] = {0xB9B7B7, 0xB9B7B7, 0x0D91D5};
const ui_theme_variable_t _ui_theme_alpha_pnlbordr[3] = {255, 255, 255};
uint8_t ui_theme_idx = UI_THEME_LIGHT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

